version: '1'

services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: simuladorcolas
      MYSQL_ROOT_PASSWORD: manager

  backend:
    image: ismaelgzse/simuladorcolas:v1.0
    ports:
      - "8443:8443"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/simuladorcolas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: manager
    depends_on:
      - db
